export interface WordEntry {
  id: string;
  english: string;
  french: string;
  spanish: string;
  german: string;
  japanese: string;
  russian: string;
  category: string;
  isCognate: boolean;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface CategoryInfo {
  id: string;
  name: string;
  description: string;
  wordCount: number;
}

// Comprehensive categorized word database
export const WORD_DATABASE: WordEntry[] = [

  // CLOTHING (50 words)
  {
    id: "clothing_001",
    english: "Shirt",
    french: "Chemise",
    spanish: "Camisa",
    german: "Hemd",
    japanese: "Shatsu",
    russian: "рубашка",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_002",
    english: "Pants",
    french: "Pantalon",
    spanish: "Pantalones",
    german: "Hose",
    japanese: "Zubon",
    russian: "брюки",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_003",
    english: "Dress",
    french: "Robe",
    spanish: "Vestido",
    german: "Kleid",
    japanese: "Doresu",
    russian: "платье",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_004",
    english: "Shoes",
    french: "Chaussures",
    spanish: "Zapatos",
    german: "Schuhe",
    japanese: "Kutsu",
    russian: "обувь",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_005",
    english: "Hat",
    french: "Chapeau",
    spanish: "Sombrero",
    german: "Hut",
    japanese: "Bōshi",
    russian: "шляпа",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_006",
    english: "Jacket",
    french: "Veste",
    spanish: "Chaqueta",
    german: "Jacke",
    japanese: "Jaketto",
    russian: "куртка",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_007",
    english: "Socks",
    french: "Chaussettes",
    spanish: "Calcetines",
    german: "Socken",
    japanese: "Kutsushita",
    russian: "носки",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_008",
    english: "Gloves",
    french: "Gants",
    spanish: "Guantes",
    german: "Handschuhe",
    japanese: "Tebukuro",
    russian: "перчатки",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_009",
    english: "Scarf",
    french: "Écharpe",
    spanish: "Bufanda",
    german: "Schal",
    japanese: "Sukāfu",
    russian: "шарф",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_010",
    english: "Sweater",
    french: "Pull",
    spanish: "Suéter",
    german: "Pullover",
    japanese: "Sētā",
    russian: "свитер",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_011",
    english: "Jeans",
    french: "Jean",
    spanish: "Vaqueros",
    german: "Jeans",
    japanese: "Jīnzu",
    russian: "джинсы",
    category: "clothing",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "clothing_012",
    english: "Skirt",
    french: "Jupe",
    spanish: "Falda",
    german: "Rock",
    japanese: "Sukāto",
    russian: "юбка",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_013",
    english: "Coat",
    french: "Manteau",
    spanish: "Abrigo",
    german: "Mantel",
    japanese: "Kōto",
    russian: "пальто",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_014",
    english: "Tie",
    french: "Cravate",
    spanish: "Corbata",
    german: "Krawatte",
    japanese: "Nekutai",
    russian: "галстук",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_015",
    english: "Belt",
    french: "Ceinture",
    spanish: "Cinturón",
    german: "Gürtel",
    japanese: "Beruto",
    russian: "ремень",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_016",
    english: "Underwear",
    french: "Sous-vêtements",
    spanish: "Ropa interior",
    german: "Unterwäsche",
    japanese: "Shitagi",
    russian: "нижнее бельё",
    category: "clothing",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "clothing_017",
    english: "Pajamas",
    french: "Pyjama",
    spanish: "Pijama",
    german: "Schlafanzug",
    japanese: "Pajama",
    russian: "пижама",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_018",
    english: "Swimsuit",
    french: "Maillot de bain",
    spanish: "Traje de baño",
    german: "Badeanzug",
    japanese: "Mizugi",
    russian: "купальник",
    category: "clothing",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "clothing_019",
    english: "Uniform",
    french: "Uniforme",
    spanish: "Uniforme",
    german: "Uniform",
    japanese: "Yunifōmu",
    russian: "форма",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_020",
    english: "Boots",
    french: "Bottes",
    spanish: "Botas",
    german: "Stiefel",
    japanese: "Būtsu",
    russian: "сапоги",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_021",
    english: "T-shirt",
    french: "T-shirt",
    spanish: "Camiseta",
    german: "T-Shirt",
    japanese: "Tīshatsu",
    russian: "футболка",
    category: "clothing",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "clothing_022",
    english: "Blouse",
    french: "Blouse",
    spanish: "Blusa",
    german: "Bluse",
    japanese: "Burausu",
    russian: "блузка",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_023",
    english: "Vest",
    french: "Gilet",
    spanish: "Chaleco",
    german: "Weste",
    japanese: "Besuto",
    russian: "жилет",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_024",
    english: "Sneakers",
    french: "Baskets",
    spanish: "Zapatillas",
    german: "Turnschuhe",
    japanese: "Sunīkā",
    russian: "кроссовки",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_025",
    english: "Cap",
    french: "Casquette",
    spanish: "Gorra",
    german: "Kappe",
    japanese: "Kyappu",
    russian: "кепка",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_026",
    english: "Shorts",
    french: "Short",
    spanish: "Pantalones cortos",
    german: "Shorts",
    japanese: "Shottsu",
    russian: "шорты",
    category: "clothing",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "clothing_027",
    english: "Hoodie",
    french: "Sweat à capuche",
    spanish: "Sudadera con capucha",
    german: "Kapuzenpullover",
    japanese: "Fūdi",
    russian: "толстовка",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_028",
    english: "Raincoat",
    french: "Imperméable",
    spanish: "Impermeable",
    german: "Regenmantel",
    japanese: "Reinkōto",
    russian: "дождевик",
    category: "clothing",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "clothing_029",
    english: "Sandals",
    french: "Sandales",
    spanish: "Sandalias",
    german: "Sandalen",
    japanese: "Sandaru",
    russian: "сандалии",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_030",
    english: "Suit",
    french: "Costume",
    spanish: "Traje",
    german: "Anzug",
    japanese: "Sūtsu",
    russian: "костюм",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_031",
    english: "Blazer",
    french: "Blazer",
    spanish: "Blazer",
    german: "Blazer",
    japanese: "Burēzā",
    russian: "блейзер",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_032",
    english: "Apron",
    french: "Tablier",
    spanish: "Delantal",
    german: "Schürze",
    japanese: "Epuron",
    russian: "фартук",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_033",
    english: "Mittens",
    french: "Moufles",
    spanish: "Manoplas",
    german: "Fäustlinge",
    japanese: "Mitten",
    russian: "варежки",
    category: "clothing",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "clothing_034",
    english: "Sweatshirt",
    french: "Sweatshirt",
    spanish: "Sudadera",
    german: "Sweatshirt",
    japanese: "Suwetto",
    russian: "свитшот",
    category: "clothing",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "clothing_035",
    english: "Leggings",
    french: "Leggings",
    spanish: "Leggings",
    german: "Leggings",
    japanese: "Reginsu",
    russian: "леггинсы",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_036",
    english: "Cardigan",
    french: "Cardigan",
    spanish: "Cárdigan",
    german: "Cardigan",
    japanese: "Kādeigan",
    russian: "кардиган",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_037",
    english: "Overalls",
    french: "Salopette",
    spanish: "Peto",
    german: "Latzhose",
    japanese: "Ōbāōru",
    russian: "комбинезон",
    category: "clothing",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "clothing_038",
    english: "Poncho",
    french: "Poncho",
    spanish: "Poncho",
    german: "Poncho",
    japanese: "Poncho",
    russian: "пончо",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_039",
    english: "Slippers",
    french: "Pantoufles",
    spanish: "Zapatillas",
    german: "Hausschuhe",
    japanese: "Surippā",
    russian: "тапочки",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_040",
    english: "Beret",
    french: "Béret",
    spanish: "Boina",
    german: "Barett",
    japanese: "Berē",
    russian: "берет",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_041",
    english: "Tights",
    french: "Collants",
    spanish: "Medias",
    german: "Strumpfhose",
    japanese: "Taitsu",
    russian: "колготки",
    category: "clothing",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "clothing_042",
    english: "Bowtie",
    french: "Noeud papillon",
    spanish: "Pajarita",
    german: "Fliege",
    japanese: "Bōtai",
    russian: "галстук-бабочка",
    category: "clothing",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "clothing_043",
    english: "Robe",
    french: "Peignoir",
    spanish: "Bata",
    german: "Morgenmantel",
    japanese: "Rōbu",
    russian: "халат",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_044",
    english: "Suspenders",
    french: "Bretelles",
    spanish: "Tirantes",
    german: "Hosenträger",
    japanese: "Sasupendā",
    russian: "подтяжки",
    category: "clothing",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "clothing_045",
    english: "Parka",
    french: "Parka",
    spanish: "Parka",
    german: "Parka",
    japanese: "Pāka",
    russian: "парка",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_046",
    english: "Tank top",
    french: "Débardeur",
    spanish: "Camiseta sin mangas",
    german: "Tanktop",
    japanese: "Tanku toppu",
    russian: "майка",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_047",
    english: "Bandana",
    french: "Bandana",
    spanish: "Bandana",
    german: "Bandana",
    japanese: "Bandana",
    russian: "бандана",
    category: "clothing",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "clothing_048",
    english: "Tracksuit",
    french: "Survêtement",
    spanish: "Chándal",
    german: "Trainingsanzug",
    japanese: "Torakkusūto",
    russian: "спортивный костюм",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "clothing_049",
    english: "Glasses",
    french: "Lunettes",
    spanish: "Gafas",
    german: "Brille",
    japanese: "Megane",
    russian: "очки",
    category: "clothing",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "clothing_050",
    english: "Necklace",
    french: "Collier",
    spanish: "Collar",
    german: "Halskette",
    japanese: "Nekkuresu",
    russian: "ожерелье",
    category: "clothing",
    isCognate: false,
    difficulty: "medium"
  },

  // SPORTS (50 words)
  {
    id: "sport_001",
    english: "Football",
    french: "Football",
    spanish: "Fútbol",
    german: "Fußball",
    japanese: "Sakkā",
    russian: "футбол",
    category: "sports",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "sport_002",
    english: "Basketball",
    french: "Basketball",
    spanish: "Baloncesto",
    german: "Basketball",
    japanese: "Basukettobōru",
    russian: "баскетбол",
    category: "sports",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "sport_003",
    english: "Tennis",
    french: "Tennis",
    spanish: "Tenis",
    german: "Tennis",
    japanese: "Tenisu",
    russian: "теннис",
    category: "sports",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "sport_004",
    english: "Swimming",
    french: "Natation",
    spanish: "Natación",
    german: "Schwimmen",
    japanese: "Suiei",
    russian: "плавание",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_005",
    english: "Running",
    french: "Course",
    spanish: "Correr",
    german: "Laufen",
    japanese: "Raningu",
    russian: "бег",
    category: "sports",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "sport_006",
    english: "Baseball",
    french: "Baseball",
    spanish: "Béisbol",
    german: "Baseball",
    japanese: "Yakyū",
    russian: "бейсбол",
    category: "sports",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "sport_007",
    english: "Volleyball",
    french: "Volleyball",
    spanish: "Voleibol",
    german: "Volleyball",
    japanese: "Barēbōru",
    russian: "волейбол",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_008",
    english: "Golf",
    french: "Golf",
    spanish: "Golf",
    german: "Golf",
    japanese: "Gorufu",
    russian: "гольф",
    category: "sports",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "sport_009",
    english: "Boxing",
    french: "Boxe",
    spanish: "Boxeo",
    german: "Boxen",
    japanese: "Bokushingu",
    russian: "бокс",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_010",
    english: "Cycling",
    french: "Cyclisme",
    spanish: "Ciclismo",
    german: "Radfahren",
    japanese: "Saikuringu",
    russian: "велоспорт",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_011",
    english: "Skiing",
    french: "Ski",
    spanish: "Esquí",
    german: "Skifahren",
    japanese: "Sukī",
    russian: "лыжи",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_012",
    english: "Hockey",
    french: "Hockey",
    spanish: "Hockey",
    german: "Hockey",
    japanese: "Hokkē",
    russian: "хоккей",
    category: "sports",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "sport_013",
    english: "Wrestling",
    french: "Lutte",
    spanish: "Lucha",
    german: "Ringen",
    japanese: "Resuringu",
    russian: "борьба",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_014",
    english: "Gymnastics",
    french: "Gymnastique",
    spanish: "Gimnasia",
    german: "Gymnastik",
    japanese: "Taisō",
    russian: "гимнастика",
    category: "sports",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "sport_015",
    english: "Martial arts",
    french: "Arts martiaux",
    spanish: "Artes marciales",
    german: "Kampfsport",
    japanese: "Budō",
    russian: "боевые искусства",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_016",
    english: "Surfing",
    french: "Surf",
    spanish: "Surf",
    german: "Surfen",
    japanese: "Sāfin",
    russian: "сёрфинг",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_017",
    english: "Climbing",
    french: "Escalade",
    spanish: "Escalada",
    german: "Klettern",
    japanese: "Kuraimingu",
    russian: "скалолазание",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_018",
    english: "Fishing",
    french: "Pêche",
    spanish: "Pesca",
    german: "Angeln",
    japanese: "Tsuri",
    russian: "рыбалка",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_019",
    english: "Dancing",
    french: "Danse",
    spanish: "Baile",
    german: "Tanzen",
    japanese: "Dansu",
    russian: "танцы",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_020",
    english: "Yoga",
    french: "Yoga",
    spanish: "Yoga",
    german: "Yoga",
    japanese: "Yoga",
    russian: "йога",
    category: "sports",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "sport_021",
    english: "Soccer",
    french: "Football",
    spanish: "Fútbol",
    german: "Fußball",
    japanese: "Sakkā",
    russian: "футбол",
    category: "sports",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "sport_022",
    english: "Rugby",
    french: "Rugby",
    spanish: "Rugby",
    german: "Rugby",
    japanese: "Ragubī",
    russian: "регби",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_023",
    english: "Badminton",
    french: "Badminton",
    spanish: "Bádminton",
    german: "Badminton",
    japanese: "Badominton",
    russian: "бадминтон",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_024",
    english: "Table tennis",
    french: "Tennis de table",
    spanish: "Tenis de mesa",
    german: "Tischtennis",
    japanese: "Takkyū",
    russian: "настольный теннис",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_025",
    english: "Archery",
    french: "Tir à l'arc",
    spanish: "Tiro con arco",
    german: "Bogenschießen",
    japanese: "Kyūjutsu",
    russian: "стрельба из лука",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_026",
    english: "Fencing",
    french: "Escrime",
    spanish: "Esgrima",
    german: "Fechten",
    japanese: "Fenshingu",
    russian: "фехтование",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_027",
    english: "Karate",
    french: "Karaté",
    spanish: "Karate",
    german: "Karate",
    japanese: "Karate",
    russian: "карате",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_028",
    english: "Judo",
    french: "Judo",
    spanish: "Judo",
    german: "Judo",
    japanese: "Jūdō",
    russian: "дзюдо",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_029",
    english: "Taekwondo",
    french: "Taekwondo",
    spanish: "Taekwondo",
    german: "Taekwondo",
    japanese: "Tekondō",
    russian: "тхэквондо",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_030",
    english: "Cricket",
    french: "Cricket",
    spanish: "Críquet",
    german: "Cricket",
    japanese: "KuriKetto",
    russian: "крикет",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_031",
    english: "Skating",
    french: "Patinage",
    spanish: "Patinaje",
    german: "Schlittschuhlaufen",
    japanese: "Sukēto",
    russian: "катание на коньках",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_032",
    english: "Snowboarding",
    french: "Snowboard",
    spanish: "Snowboard",
    german: "Snowboarden",
    japanese: "Sunōbōdo",
    russian: "сноуборд",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_033",
    english: "Diving",
    french: "Plongée",
    spanish: "Buceo",
    german: "Tauchen",
    japanese: "Daibingu",
    russian: "дайвинг",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_034",
    english: "Rowing",
    french: "Aviron",
    spanish: "Remo",
    german: "Rudern",
    japanese: "Rōingu",
    russian: "гребля",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_035",
    english: "Sailing",
    french: "Voile",
    spanish: "Vela",
    german: "Segeln",
    japanese: "Sēringu",
    russian: "парусный спорт",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_036",
    english: "Horseback riding",
    french: "Équitation",
    spanish: "Equitación",
    german: "Reiten",
    japanese: "Jōba",
    russian: "верховая езда",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_037",
    english: "Weightlifting",
    french: "Haltérophilie",
    spanish: "Halterofilia",
    german: "Gewichtheben",
    japanese: "Ueitōrifutingu",
    russian: "тяжёлая атлетика",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_038",
    english: "Athletics",
    french: "Athlétisme",
    spanish: "Atletismo",
    german: "Leichtathletik",
    japanese: "Rikujō",
    russian: "лёгкая атлетика",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_039",
    english: "Triathlon",
    french: "Triathlon",
    spanish: "Triatlón",
    german: "Triathlon",
    japanese: "Toraiazuron",
    russian: "триатлон",
    category: "sports",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "sport_040",
    english: "Polo",
    french: "Polo",
    spanish: "Polo",
    german: "Polo",
    japanese: "Pōro",
    russian: "поло",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_041",
    english: "Squash",
    french: "Squash",
    spanish: "Squash",
    german: "Squash",
    japanese: "Sukuwasshu",
    russian: "сквош",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_042",
    english: "Kayaking",
    french: "Kayak",
    spanish: "Kayak",
    german: "Kajakfahren",
    japanese: "Kayakkingu",
    russian: "гребля на байдарках",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_043",
    english: "Canoeing",
    french: "Canoë",
    spanish: "Canotaje",
    german: "Kanufahren",
    japanese: "Kanūingu",
    russian: "гребля на каноэ",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_044",
    english: "Bowling",
    french: "Bowling",
    spanish: "Bolos",
    german: "Bowling",
    japanese: "Bōringu",
    russian: "боулинг",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_045",
    english: "Ice hockey",
    french: "Hockey sur glace",
    spanish: "Hockey sobre hielo",
    german: "Eishockey",
    japanese: "Aisu hokkē",
    russian: "хоккей с шайбой",
    category: "sports",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "sport_046",
    english: "Figure skating",
    french: "Patinage artistique",
    spanish: "Patinaje artístico",
    german: "Eiskunstlauf",
    japanese: "Figyua sukētingu",
    russian: "фигурное катание",
    category: "sports",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "sport_047",
    english: "Lacrosse",
    french: "Crosse",
    spanish: "Lacrosse",
    german: "Lacrosse",
    japanese: "Rakurosu",
    russian: "лакросс",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_048",
    english: "Softball",
    french: "Softball",
    spanish: "Sóftbol",
    german: "Softball",
    japanese: "Sofutobōru",
    russian: "софтбол",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_049",
    english: "Netball",
    french: "Netball",
    spanish: "Netball",
    german: "Netball",
    japanese: "Nettobōru",
    russian: "нетбол",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "sport_050",
    english: "Handball",
    french: "Handball",
    spanish: "Balonmano",
    german: "Handball",
    japanese: "Handobōru",
    russian: "гандбол",
    category: "sports",
    isCognate: true,
    difficulty: "medium"
  },

  // HOUSEHOLD ITEMS (50 words)
  {
    id: "household_001",
    english: "Table",
    french: "Table",
    spanish: "Mesa",
    german: "Tisch",
    japanese: "Tēburu",
    russian: "стол",
    category: "household",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "household_002",
    english: "Chair",
    french: "Chaise",
    spanish: "Silla",
    german: "Stuhl",
    japanese: "Isu",
    russian: "стул",
    category: "household",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "household_003",
    english: "Bed",
    french: "Lit",
    spanish: "Cama",
    german: "Bett",
    japanese: "Beddo",
    russian: "кровать",
    category: "household",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "household_004",
    english: "Sofa",
    french: "Canapé",
    spanish: "Sofá",
    german: "Sofa",
    japanese: "Sofā",
    russian: "диван",
    category: "household",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "household_005",
    english: "Television",
    french: "Télévision",
    spanish: "Televisión",
    german: "Fernseher",
    japanese: "Terebi",
    russian: "телевизор",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_006",
    english: "Refrigerator",
    french: "Réfrigérateur",
    spanish: "Refrigerador",
    german: "Kühlschrank",
    japanese: "Reizōko",
    russian: "холодильник",
    category: "household",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "household_007",
    english: "Stove",
    french: "Cuisinière",
    spanish: "Estufa",
    german: "Herd",
    japanese: "Konro",
    russian: "плита",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_008",
    english: "Microwave",
    french: "Micro-ondes",
    spanish: "Microondas",
    german: "Mikrowelle",
    japanese: "Denshirenji",
    russian: "микроволновка",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_009",
    english: "Lamp",
    french: "Lampe",
    spanish: "Lámpara",
    german: "Lampe",
    japanese: "Ranpu",
    russian: "лампа",
    category: "household",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "household_010",
    english: "Mirror",
    french: "Miroir",
    spanish: "Espejo",
    german: "Spiegel",
    japanese: "Kagami",
    russian: "зеркало",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_011",
    english: "Window",
    french: "Fenêtre",
    spanish: "Ventana",
    german: "Fenster",
    japanese: "Mado",
    russian: "окно",
    category: "household",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "household_012",
    english: "Door",
    french: "Porte",
    spanish: "Puerta",
    german: "Tür",
    japanese: "Doa",
    russian: "дверь",
    category: "household",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "household_013",
    english: "Clock",
    french: "Horloge",
    spanish: "Reloj",
    german: "Uhr",
    japanese: "Tokei",
    russian: "часы",
    category: "household",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "household_014",
    english: "Computer",
    french: "Ordinateur",
    spanish: "Computadora",
    german: "Computer",
    japanese: "Konpyūtā",
    russian: "компьютер",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_015",
    english: "Phone",
    french: "Téléphone",
    spanish: "Teléfono",
    german: "Telefon",
    japanese: "Denwa",
    russian: "телефон",
    category: "household",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "household_016",
    english: "Book",
    french: "Livre",
    spanish: "Libro",
    german: "Buch",
    japanese: "Hon",
    russian: "книга",
    category: "household",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "household_017",
    english: "Pillow",
    french: "Oreiller",
    spanish: "Almohada",
    german: "Kissen",
    japanese: "Makura",
    russian: "подушка",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_018",
    english: "Blanket",
    french: "Couverture",
    spanish: "Manta",
    german: "Decke",
    japanese: "Mōfu",
    russian: "одеяло",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_019",
    english: "Towel",
    french: "Serviette",
    spanish: "Toalla",
    german: "Handtuch",
    japanese: "Taoru",
    russian: "полотенце",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_020",
    english: "Vacuum",
    french: "Aspirateur",
    spanish: "Aspiradora",
    german: "Staubsauger",
    japanese: "Sōjiki",
    russian: "пылесос",
    category: "household",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "household_021",
    english: "Desk",
    french: "Bureau",
    spanish: "Escritorio",
    german: "Schreibtisch",
    japanese: "Desuku",
    russian: "письменный стол",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_022",
    english: "Bookshelf",
    french: "Bibliothèque",
    spanish: "Estantería",
    german: "Bücherregal",
    japanese: "Hondana",
    russian: "книжный шкаф",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_023",
    english: "Wardrobe",
    french: "Armoire",
    spanish: "Armario",
    german: "Kleiderschrank",
    japanese: "Tansu",
    russian: "гардероб",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_024",
    english: "Curtains",
    french: "Rideaux",
    spanish: "Cortinas",
    german: "Vorhänge",
    japanese: "Kāten",
    russian: "шторы",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_025",
    english: "Rug",
    french: "Tapis",
    spanish: "Alfombra",
    german: "Teppich",
    japanese: "Ragu",
    russian: "ковёр",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_026",
    english: "Fan",
    french: "Ventilateur",
    spanish: "Ventilador",
    german: "Ventilator",
    japanese: "Fan",
    russian: "вентилятор",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_027",
    english: "Heater",
    french: "Chauffage",
    spanish: "Calefactor",
    german: "Heizung",
    japanese: "Hītā",
    russian: "обогреватель",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_028",
    english: "Washing machine",
    french: "Machine à laver",
    spanish: "Lavadora",
    german: "Waschmaschine",
    japanese: "Sentakuki",
    russian: "стиральная машина",
    category: "household",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "household_029",
    english: "Dryer",
    french: "Sèche-linge",
    spanish: "Secadora",
    german: "Trockner",
    japanese: "Kansōki",
    russian: "сушилка",
    category: "household",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "household_030",
    english: "Dishwasher",
    french: "Lave-vaisselle",
    spanish: "Lavavajillas",
    german: "Geschirrspüler",
    japanese: "Shokkiarai ki",
    russian: "посудомоечная машина",
    category: "household",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "household_031",
    english: "Toaster",
    french: "Grille-pain",
    spanish: "Tostadora",
    german: "Toaster",
    japanese: "Tōsutā",
    russian: "тостер",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_032",
    english: "Blender",
    french: "Mixeur",
    spanish: "Licuadora",
    german: "Mixer",
    japanese: "Burendā",
    russian: "блендер",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_033",
    english: "Kettle",
    french: "Bouilloire",
    spanish: "Hervidor",
    german: "Wasserkocher",
    japanese: "Kettoru",
    russian: "чайник",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_034",
    english: "Oven",
    french: "Four",
    spanish: "Horno",
    german: "Ofen",
    japanese: "Ōbun",
    russian: "духовка",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_035",
    english: "Mattress",
    french: "Matelas",
    spanish: "Colchón",
    german: "Matratze",
    japanese: "Mattoresu",
    russian: "матрас",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_036",
    english: "Couch",
    french: "Canapé",
    spanish: "Sofá",
    german: "Couch",
    japanese: "Kauchi",
    russian: "диван",
    category: "household",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "household_037",
    english: "Cabinet",
    french: "Armoire",
    spanish: "Gabinete",
    german: "Schrank",
    japanese: "Kyabinetto",
    russian: "шкаф",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_038",
    english: "Sink",
    french: "Évier",
    spanish: "Fregadero",
    german: "Spüle",
    japanese: "Shinku",
    russian: "раковина",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_039",
    english: "Faucet",
    french: "Robinet",
    spanish: "Grifo",
    german: "Wasserhahn",
    japanese: "Jagūchi",
    russian: "кран",
    category: "household",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "household_040",
    english: "Carpet",
    french: "Moquette",
    spanish: "Alfombra",
    german: "Teppich",
    japanese: "Kāpetto",
    russian: "ковёр",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_041",
    english: "Broom",
    french: "Balai",
    spanish: "Escoba",
    german: "Besen",
    japanese: "Hōki",
    russian: "метла",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_042",
    english: "Mop",
    french: "Serpillière",
    spanish: "Fregona",
    german: "Wischmopp",
    japanese: "Moppu",
    russian: "швабра",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_043",
    english: "Trash can",
    french: "Poubelle",
    spanish: "Basurero",
    german: "Mülleimer",
    japanese: "Gomibako",
    russian: "мусорное ведро",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_044",
    english: "Light bulb",
    french: "Ampoule",
    spanish: "Bombilla",
    german: "Glühbirne",
    japanese: "Denkyū",
    russian: "лампочка",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_045",
    english: "Iron",
    french: "Fer à repasser",
    spanish: "Plancha",
    german: "Bügeleisen",
    japanese: "Airon",
    russian: "утюг",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_046",
    english: "Ironing board",
    french: "Table à repasser",
    spanish: "Tabla de planchar",
    german: "Bügelbrett",
    japanese: "Airon dai",
    russian: "гладильная доска",
    category: "household",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "household_047",
    english: "Vase",
    french: "Vase",
    spanish: "Jarrón",
    german: "Vase",
    japanese: "Kabin",
    russian: "ваза",
    category: "household",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "household_048",
    english: "Cushion",
    french: "Coussin",
    spanish: "Cojín",
    german: "Kissen",
    japanese: "Kusshon",
    russian: "подушка",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_049",
    english: "Candle",
    french: "Bougie",
    spanish: "Vela",
    german: "Kerze",
    japanese: "Rōsoku",
    russian: "свеча",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "household_050",
    english: "Remote control",
    french: "Télécommande",
    spanish: "Control remoto",
    german: "Fernbedienung",
    japanese: "Rimokon",
    russian: "пульт дистанционного управления",
    category: "household",
    isCognate: false,
    difficulty: "medium"
  }
  // COLORS (50 words)
  {
    id: "color_001",
    english: "Red",
    french: "Rouge",
    spanish: "Rojo",
    german: "Rot",
    japanese: "Aka",
    russian: "красный",
    category: "colors",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "color_002",
    english: "Blue",
    french: "Bleu",
    spanish: "Azul",
    german: "Blau",
    japanese: "Ao",
    russian: "синий",
    category: "colors",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "color_003",
    english: "Green",
    french: "Vert",
    spanish: "Verde",
    german: "Grün",
    japanese: "Midori",
    russian: "зелёный",
    category: "colors",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "color_004",
    english: "Yellow",
    french: "Jaune",
    spanish: "Amarillo",
    german: "Gelb",
    japanese: "Kiiro",
    russian: "жёлтый",
    category: "colors",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "color_005",
    english: "Black",
    french: "Noir",
    spanish: "Negro",
    german: "Schwarz",
    japanese: "Kuro",
    russian: "чёрный",
    category: "colors",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "color_006",
    english: "White",
    french: "Blanc",
    spanish: "Blanco",
    german: "Weiß",
    japanese: "Shiro",
    russian: "белый",
    category: "colors",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "color_007",
    english: "Orange",
    french: "Orange",
    spanish: "Naranja",
    german: "Orange",
    japanese: "Orenji",
    russian: "оранжевый",
    category: "colors",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "color_008",
    english: "Purple",
    french: "Violet",
    spanish: "Morado",
    german: "Lila",
    japanese: "Murasaki",
    russian: "фиолетовый",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_009",
    english: "Pink",
    french: "Rose",
    spanish: "Rosa",
    german: "Rosa",
    japanese: "Pinku",
    russian: "розовый",
    category: "colors",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "color_010",
    english: "Brown",
    french: "Marron",
    spanish: "Marrón",
    german: "Braun",
    japanese: "Chairo",
    russian: "коричневый",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_011",
    english: "Gray",
    french: "Gris",
    spanish: "Gris",
    german: "Grau",
    japanese: "Haiiro",
    russian: "серый",
    category: "colors",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "color_012",
    english: "Silver",
    french: "Argent",
    spanish: "Plata",
    german: "Silber",
    japanese: "Gin",
    russian: "серебряный",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_013",
    english: "Gold",
    french: "Or",
    spanish: "Oro",
    german: "Gold",
    japanese: "Kin",
    russian: "золотой",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_014",
    english: "Beige",
    french: "Beige",
    spanish: "Beige",
    german: "Beige",
    japanese: "Bēju",
    russian: "бежевый",
    category: "colors",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "color_015",
    english: "Turquoise",
    french: "Turquoise",
    spanish: "Turquesa",
    german: "Türkis",
    japanese: "Tākōizu",
    russian: "бирюзовый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_016",
    english: "Maroon",
    french: "Bordeaux",
    spanish: "Granate",
    german: "Kastanienbraun",
    japanese: "Marūn",
    russian: "бордовый",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_017",
    english: "Navy",
    french: "Bleu marine",
    spanish: "Azul marino",
    german: "Marineblau",
    japanese: "Nēbī",
    russian: "тёмно-синий",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_018",
    english: "Lime",
    french: "Vert citron",
    spanish: "Lima",
    german: "Limette",
    japanese: "Raimu",
    russian: "лаймовый",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_019",
    english: "Coral",
    french: "Corail",
    spanish: "Coral",
    german: "Koralle",
    japanese: "Koraru",
    russian: "коралловый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_020",
    english: "Ivory",
    french: "Ivoire",
    spanish: "Marfil",
    german: "Elfenbein",
    japanese: "Aibōrī",
    russian: "слоновая кость",
    category: "colors",
    isCognate: false,
   owały кость",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_021",
    english: "Teal",
    french: "Sarcelle",
    spanish: "Verde azulado",
    german: "Petrol",
    japanese: "Tīru",
    russian: "бирюзово-зелёный",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_022",
    english: "Magenta",
    french: "Magenta",
    spanish: "Magenta",
    german: "Magenta",
    japanese: "Majenta",
    russian: "пурпурный",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_023",
    english: "Violet",
    french: "Violette",
    spanish: "Violeta",
    german: "Violett",
    japanese: "Sumire",
    russian: "фиолетовый",
    category: "colors",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "color_024",
    english: "Indigo",
    french: "Indigo",
    spanish: "Índigo",
    german: "Indigo",
    japanese: "Indigo",
    russian: "индиго",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_025",
    english: "Crimson",
    french: "Cramoisi",
    spanish: "Carmesí",
    german: "Karmesinrot",
    japanese: "Kurenai",
    russian: "малиновый",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_026",
    english: "Amber",
    french: "Ambre",
    spanish: "Ámbar",
    german: "Bernstein",
    japanese: "Kohaku",
    russian: "янтарный",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_027",
    english: "Olive",
    french: "Olive",
    spanish: "Oliva",
    german: "Oliv",
    japanese: "Orību",
    russian: "оливковый",
    category: "colors",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "color_028",
    english: "Mint",
    french: "Menthe",
    spanish: "Menta",
    german: "Minze",
    japanese: "Minto",
    russian: "мятный",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_029",
    english: "Peach",
    french: "Pêche",
    spanish: "Melocotón",
    german: "Pfirsich",
    japanese: "Pīchi",
    russian: "персиковый",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_030",
    english: "Lavender",
    french: "Lavande",
    spanish: "Lavanda",
    german: "Lavendel",
    japanese: "Rabendā",
    russian: "лавандовый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_031",
    english: "Saffron",
    french: "Safran",
    spanish: "Azafrán",
    german: "Safran",
    japanese: "Safuran",
    russian: "шафрановый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_032",
    english: "Ebony",
    french: "Ébène",
    spanish: "Ébano",
    german: "Ebenholz",
    japanese: "Ebonī",
    russian: "чёрное дерево",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_033",
    english: "Emerald",
    french: "Émeraude",
    spanish: "Esmeralda",
    german: "Smaragd",
    japanese: "Emerarudo",
    russian: "изумрудный",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_034",
    english: "Ruby",
    french: "Rubis",
    spanish: "Rubí",
    german: "Rubin",
    japanese: "Rubī",
    russian: "рубиновый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_035",
    english: "Sapphire",
    french: "Saphir",
    spanish: "Zafiro",
    german: "Saphir",
    japanese: "Safaiya",
    russian: "сапфировый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_036",
    english: "Bronze",
    french: "Bronze",
    spanish: "Bronce",
    german: "Bronze",
    japanese: "Buronzū",
    russian: "бронзовый",
    category: "colors",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "color_037",
    english: "Copper",
    french: "Cuivre",
    spanish: "Cobre",
    german: "Kupfer",
    japanese: "Dō",
    russian: "медный",
    category: "colors",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "color_038",
    english: "Plum",
    french: "Prune",
    spanish: "Ciruela",
    german: "Pflaume",
    japanese: "Puramu",
    russian: "сливовый",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_039",
    english: "Charcoal",
    french: "Charbon",
    spanish: "Carbón",
    german: "Holzkohle",
    japanese: "Sumī",
    russian: "угольно-чёрный",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_040",
    english: "Slate",
    french: "Ardoise",
    spanish: "Pizarra",
    german: "Schiefer",
    japanese: "Surēto",
    russian: "шиферный",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_041",
    english: "Tangerine",
    french: "Tangerine",
    spanish: "Mandarina",
    german: "Mandarine",
    japanese: "Tangarīn",
    russian: "мандариновый",
    category: "colors",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "color_042",
    english: "Fuchsia",
    french: "Fuchsia",
    spanish: "Fucsia",
    german: "Fuchsia",
    japanese: "Fushia",
    russian: "фуксия",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_043",
    english: "Mauve",
    french: "Mauve",
    spanish: "Malva",
    german: "Malve",
    japanese: "Mōbu",
    russian: "лиловый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_044",
    english: "Aqua",
    french: "Aqua",
    spanish: "Aguamarina",
    german: "Aqua",
    japanese: "Akua",
    russian: "аква",
    category: "colors",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "color_045",
    english: "Lilac",
    french: "Lilas",
    spanish: "Lila",
    german: "Flieder",
    japanese: "Rairakku",
    russian: "сиреневый",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_046",
    english: "Khaki",
    french: "Kaki",
    spanish: "Caqui",
    german: "Khaki",
    japanese: "Kāki",
    russian: "хаки",
    category: "colors",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "color_047",
    english: "Ochre",
    french: "Ocre",
    spanish: "Ocre",
    german: "Ocker",
    japanese: "Ōkā",
    russian: "охристый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_048",
    english: "Sepia",
    french: "Sépia",
    spanish: "Sepia",
    german: "Sepia",
    japanese: "Sepia",
    russian: "сепия",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "color_049",
    english: "Cerulean",
    french: "Céruléen",
    spanish: "Cerúleo",
    german: "Himmelblau",
    japanese: "Serurian",
    russian: "голубой",
    category: "colors",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "color_050",
    english: "Jade",
    french: "Jade",
    spanish: "Jade",
    german: "Jade",
    japanese: "Hisui",
    russian: "нефритовый",
    category: "colors",
    isCognate: true,
    difficulty: "hard"
  },

  // ANIMALS (50 words)
  {
    id: "animal_001",
    english: "Cat",
    french: "Chat",
    spanish: "Gato",
    german: "Katze",
    japanese: "Neko",
    russian: "кот",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_002",
    english: "Dog",
    french: "Chien",
    spanish: "Perro",
    german: "Hund",
    japanese: "Inu",
    russian: "собака",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_003",
    english: "Bird",
    french: "Oiseau",
    spanish: "Pájaro",
    german: "Vogel",
    japanese: "Tori",
    russian: "птица",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_004",
    english: "Fish",
    french: "Poisson",
    spanish: "Pez",
    german: "Fisch",
    japanese: "Sakana",
    russian: "рыба",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_005",
    english: "Horse",
    french: "Cheval",
    spanish: "Caballo",
    german: "Pferd",
    japanese: "Uma",
    russian: "лошадь",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_006",
    english: "Cow",
    french: "Vache",
    spanish: "Vaca",
    german: "Kuh",
    japanese: "Ushi",
    russian: "корова",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_007",
    english: "Pig",
    french: "Cochon",
    spanish: "Cerdo",
    german: "Schwein",
    japanese: "Buta",
    russian: "свинья",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_008",
    english: "Sheep",
    french: "Mouton",
    spanish: "Oveja",
    german: "Schaf",
    japanese: "Hitsuji",
    russian: "овца",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_009",
    english: "Lion",
    french: "Lion",
    spanish: "León",
    german: "Löwe",
    japanese: "Raion",
    russian: "лев",
    category: "animals",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "animal_010",
    english: "Tiger",
    french: "Tigre",
    spanish: "Tigre",
    german: "Tiger",
    japanese: "Tora",
    russian: "тигр",
    category: "animals",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "animal_011",
    english: "Elephant",
    french: "Éléphant",
    spanish: "Elefante",
    german: "Elefant",
    japanese: "Zō",
    russian: "слон",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_012",
    english: "Monkey",
    french: "Singe",
    spanish: "Mono",
    german: "Affe",
    japanese: "Saru",
    russian: "обезьяна",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_013",
    english: "Bear",
    french: "Ours",
    spanish: "Oso",
    german: "Bär",
    japanese: "Kuma",
    russian: "медведь",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_014",
    english: "Wolf",
    french: "Loup",
    spanish: "Lobo",
    german: "Wolf",
    japanese: "Ōkami",
    russian: "волк",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_015",
    english: "Fox",
    french: "Renard",
    spanish: "Zorro",
    german: "Fuchs",
    japanese: "Kitsune",
    russian: "лиса",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_016",
    english: "Rabbit",
    french: "Lapin",
    spanish: "Conejo",
    german: "Kaninchen",
    japanese: "Usagi",
    russian: "кролик",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_017",
    english: "Mouse",
    french: "Souris",
    spanish: "Ratón",
    german: "Maus",
    japanese: "Nezumi",
    russian: "мышь",
    category: "animals",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "animal_018",
    english: "Snake",
    french: "Serpent",
    spanish: "Serpiente",
    german: "Schlange",
    japanese: "Hebi",
    russian: "змея",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_019",
    english: "Turtle",
    french: "Tortue",
    spanish: "Tortuga",
    german: "Schildkröte",
    japanese: "Kame",
    russian: "черепаха",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_020",
    english: "Frog",
    french: "Grenouille",
    spanish: "Rana",
    german: "Frosch",
    japanese: "Kaeru",
    russian: "лягушка",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_021",
    english: "Butterfly",
    french: "Papillon",
    spanish: "Mariposa",
    german: "Schmetterling",
    japanese: "Chō",
    russian: "бабочка",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_022",
    english: "Bee",
    french: "Abeille",
    spanish: "Abeja",
    german: "Biene",
    japanese: "Hachi",
    russian: "пчела",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_023",
    english: "Spider",
    french: "Araignée",
    spanish: "Araña",
    german: "Spinne",
    japanese: "Kumo",
    russian: "паук",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_024",
    english: "Dolphin",
    french: "Dauphin",
    spanish: "Delfín",
    german: "Delfin",
    japanese: "Iruka",
    russian: "дельфин",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_025",
    english: "Penguin",
    french: "Pingouin",
    spanish: "Pingüino",
    german: "Pinguin",
    japanese: "Pengin",
    russian: "пингвин",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_026",
    english: "Deer",
    french: "Cerf",
    spanish: "Ciervo",
    german: "Hirsch",
    japanese: "Shika",
    russian: "олень",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_027",
    english: "Giraffe",
    french: "Girafe",
    spanish: "Jirafa",
    german: "Giraffe",
    japanese: "Kirin",
    russian: "жираф",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_028",
    english: "Zebra",
    french: "Zèbre",
    spanish: "Cebra",
    german: "Zebra",
    japanese: "Shimauma",
    russian: "зебра",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_029",
    english: "Rhinoceros",
    french: "Rhinocéros",
    spanish: "Rinoceronte",
    german: "Nashorn",
    japanese: "Sai",
    russian: "носорог",
    category: "animals",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "animal_030",
    english: "Hippopotamus",
    french: "Hippopotame",
    spanish: "Hipopótamo",
    german: "Nilpferd",
    japanese: "Kaba",
    russian: "гиппопотам",
    category: "animals",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "animal_031",
    english: "Crocodile",
    french: "Crocodile",
    spanish: "Cocodrilo",
    german: "Krokodil",
    japanese: "Wani",
    russian: "крокодил",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_032",
    english: "Alligator",
    french: "Alligator",
    spanish: "Caimán",
    german: "Alligator",
    japanese: "Arigētā",
    russian: "аллигатор",
    category: "animals",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "animal_033",
    english: "Kangaroo",
    french: "Kangourou",
    spanish: "Canguro",
    german: "Känguru",
    japanese: "Kangarū",
    russian: "кенгуру",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_034",
    english: "Panda",
    french: "Panda",
    spanish: "Panda",
    german: "Panda",
    japanese: "Panda",
    russian: "панда",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_035",
    english: "Koala",
    french: "Koala",
    spanish: "Koala",
    german: "Koala",
    japanese: "Koara",
    russian: "коала",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_036",
    english: "Cheetah",
    french: "Guépard",
    spanish: "Guepardo",
    german: "Gepard",
    japanese: "Chītā",
    russian: "гепард",
    category: "animals",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "animal_037",
    english: "Leopard",
    french: "Léopard",
    spanish: "Leopardo",
    german: "Leopard",
    japanese: "Hyō",
    russian: "леопард",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_038",
    english: "Gorilla",
    french: "Gorille",
    spanish: "Gorila",
    german: "Gorilla",
    japanese: "Gorira",
    russian: "горилла",
    category: "animals",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "animal_039",
    english: "Chimpanzee",
    french: "Chimpanzé",
    spanish: "Chimpancé",
    german: "Schimpanse",
    japanese: "Chinpanjī",
    russian: "шимпанзе",
    category: "animals",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "animal_040",
    english: "Ostrich",
    french: "Autruche",
    spanish: "Avestruz",
    german: "Strauß",
    japanese: "Dachō",
    russian: "страус",
    category: "animals",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "animal_041",
    english: "Eagle",
    french: "Aigle",
    spanish: "Águila",
    german: "Adler",
    japanese: "Washi",
    russian: "орёл",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_042",
    english: "Hawk",
    french: "Faucon",
    spanish: "Halcón",
    german: "Falke",
    japanese: "Taka",
    russian: "ястреб",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_043",
    english: "Owl",
    french: "Hibou",
    spanish: "Búho",
    german: "Eule",
    japanese: "Fukurō",
    russian: "сова",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_044",
    english: "Parrot",
    french: "Perroquet",
    spanish: "Loro",
    german: "Papagei",
    japanese: "Ōmu",
    russian: "попугай",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_045",
    english: "Shark",
    french: "Requin",
    spanish: "Tiburón",
    german: "Hai",
    japanese: "Same",
    russian: "акула",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_046",
    english: "Whale",
    french: "Baleine",
    spanish: "Ballena",
    german: "Wal",
    japanese: "Kujira",
    russian: "кит",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_047",
    english: "Seal",
    french: "Phoque",
    spanish: "Foca",
    german: "Seehund",
    japanese: "Azarashi",
    russian: "тюлень",
    category: "animals",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "animal_048",
    english: "Jellyfish",
    french: "Méduse",
    spanish: "Medusa",
    german: "Qualle",
    japanese: "Kurage",
    russian: "медуза",
    category: "animals",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "animal_049",
    english: "Octopus",
    french: "Poulpe",
    spanish: "Pulpo",
    german: "Oktopus",
    japanese: "Tako",
    russian: "осьминог",
    category: "animals",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "animal_050",
    english: "Squid",
    french: "Calmar",
    spanish: "Calamar",
    german: "Tintenfisch",
    japanese: "Ika",
    russian: "кальмар",
    category: "animals",
    isCognate: true,
    difficulty: "hard"
  },

  // FOOD (50 words)
  {
    id: "food_001",
    english: "Apple",
    french: "Pomme",
    spanish: "Manzana",
    german: "Apfel",
    japanese: "Ringo",
    russian: "яблоко",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_002",
    english: "Banana",
    french: "Banane",
    spanish: "Plátano",
    german: "Banane",
    japanese: "Banana",
    russian: "банан",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_003",
    english: "Orange",
    french: "Orange",
    spanish: "Naranja",
    german: "Orange",
    japanese: "Orenji",
    russian: "апельсин",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_004",
    english: "Bread",
    french: "Pain",
    spanish: "Pan",
    german: "Brot",
    japanese: "Pan",
    russian: "хлеб",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_005",
    english: "Milk",
    french: "Lait",
    spanish: "Leche",
    german: "Milch",
    japanese: "Gyūnyū",
    russian: "молоко",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_006",
    english: "Cheese",
    french: "Fromage",
    spanish: "Queso",
    german: "Käse",
    japanese: "Chīzu",
    russian: "сыр",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_007",
    english: "Egg",
    french: "Œuf",
    spanish: "Huevo",
    german: "Ei",
    japanese: "Tamago",
    russian: "яйцо",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_008",
    english: "Meat",
    french: "Viande",
    spanish: "Carne",
    german: "Fleisch",
    japanese: "Niku",
    russian: "мясо",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_009",
    english: "Fish",
    french: "Poisson",
    spanish: "Pescado",
    german: "Fisch",
    japanese: "Sakana",
    russian: "рыба",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_010",
    english: "Rice",
    french: "Riz",
    spanish: "Arroz",
    german: "Reis",
    japanese: "Gohan",
    russian: "рис",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_011",
    english: "Pasta",
    french: "Pâtes",
    spanish: "Pasta",
    german: "Nudeln",
    japanese: "Pasuta",
    russian: "паста",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_012",
    english: "Pizza",
    french: "Pizza",
    spanish: "Pizza",
    german: "Pizza",
    japanese: "Piza",
    russian: "пицца",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_013",
    english: "Salad",
    french: "Salade",
    spanish: "Ensalada",
    german: "Salat",
    japanese: "Sarada",
    russian: "салат",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_014",
    english: "Soup",
    french: "Soupe",
    spanish: "Sopa",
    german: "Suppe",
    japanese: "Sūpu",
    russian: "суп",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_015",
    english: "Sandwich",
    french: "Sandwich",
    spanish: "Sándwich",
    german: "Sandwich",
    japanese: "Sandoitchi",
    russian: "сэндвич",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_016",
    english: "Chocolate",
    french: "Chocolat",
    spanish: "Chocolate",
    german: "Schokolade",
    japanese: "Chokorēto",
    russian: "шоколад",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_017",
    english: "Coffee",
    french: "Café",
    spanish: "Café",
    german: "Kaffee",
    japanese: "Kōhī",
    russian: "кофе",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_018",
    english: "Tea",
    french: "Thé",
    spanish: "Té",
    german: "Tee",
    japanese: "Cha",
    russian: "чай",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_019",
    english: "Water",
    french: "Eau",
    spanish: "Agua",
    german: "Wasser",
    japanese: "Mizu",
    russian: "вода",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_020",
    english: "Juice",
    french: "Jus",
    spanish: "Jugo",
    german: "Saft",
    japanese: "Jūsu",
    russian: "сок",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_021",
    english: "Potato",
    french: "Pomme de terre",
    spanish: "Patata",
    german: "Kartoffel",
    japanese: "Jagaimo",
    russian: "картофель",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_022",
    english: "Tomato",
    french: "Tomate",
    spanish: "Tomate",
    german: "Tomate",
    japanese: "Tomato",
    russian: "помидор",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_023",
    english: "Carrot",
    french: "Carotte",
    spanish: "Zanahoria",
    german: "Karotte",
    japanese: "Ninjin",
    russian: "морковь",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_024",
    english: "Onion",
    french: "Oignon",
    spanish: "Cebolla",
    german: "Zwiebel",
    japanese: "Tamanegi",
    russian: "лук",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_025",
    english: "Garlic",
    french: "Ail",
    spanish: "Ajo",
    german: "Knoblauch",
    japanese: "Ninniku",
    russian: "чеснок",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_026",
    english: "Broccoli",
    french: "Brocoli",
    spanish: "Brócoli",
    german: "Brokkoli",
    japanese: "Burokkori",
    russian: "брокколи",
    category: "food",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "food_027",
    english: "Lettuce",
    french: "Laitue",
    spanish: "Lechuga",
    german: "Salat",
    japanese: "Retasu",
    russian: "салат",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_028",
    english: "Cucumber",
    french: "Concombre",
    spanish: "Pepino",
    german: "Gurke",
    japanese: "Kyūri",
    russian: "огурец",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_029",
    english: "Spinach",
    french: "Épinard",
    spanish: "Espinaca",
    german: "Spinat",
    japanese: "Hōrensō",
    russian: "шпинат",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_030",
    english: "Mushroom",
    french: "Champignon",
    spanish: "Champiñón",
    german: "Pilz",
    japanese: "Kinoko",
    russian: "гриб",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_031",
    english: "Corn",
    french: "Maïs",
    spanish: "Maíz",
    german: "Mais",
    japanese: "Tōmorokoshi",
    russian: "кукуруза",
    category: "food",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "food_032",
    english: "Peas",
    french: "Petits pois",
    spanish: "Guisantes",
    german: "Erbsen",
    japanese: "Endō",
    russian: "горох",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_033",
    english: "Beans",
    french: "Haricots",
    spanish: "Frijoles",
    german: "Bohnen",
    japanese: "Mame",
    russian: "бобы",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_034",
    english: "Chicken",
    french: "Poulet",
    spanish: "Pollo",
    german: "Huhn",
    japanese: "Tori",
    russian: "курица",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_035",
    english: "Beef",
    french: "Bœuf",
    spanish: "Carne de res",
    german: "Rindfleisch",
    japanese: "Gyūniku",
    russian: "говядина",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_036",
    english: "Pork",
    french: "Porc",
    spanish: "Cerdo",
    german: "Schweinefleisch",
    japanese: "Butaniku",
    russian: "свинина",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_037",
    english: "Salmon",
    french: "Saumon",
    spanish: "Salmón",
    german: "Lachs",
    japanese: "Sāmon",
    russian: "лосось",
    category: "food",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "food_038",
    english: "Shrimp",
    french: "Crevette",
    spanish: "Camarón",
    german: "Garnele",
    japanese: "Ebi",
    russian: "креветка",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "food_039",
    english: "Tuna",
    french: "Thon",
    spanish: "Atún",
    german: "Thunfisch",
    japanese: "Maguro",
    russian: "тунец",
    category: "food",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "food_040",
    english: "Bread",
    french: "Pain",
    spanish: "Pan",
    german: "Brot",
    japanese: "Pan",
    russian: "хлеб",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_041",
    english: "Butter",
    french: "Beurre",
    spanish: "Mantequilla",
    german: "Butter",
    japanese: "Batā",
    russian: "масло",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_042",
    english: "Honey",
    french: "Miel",
    spanish: "Miel",
    german: "Honig",
    japanese: "Hachimitsu",
    russian: "мёд",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_043",
    english: "Sugar",
    french: "Sucre",
    spanish: "Azúcar",
    german: "Zucker",
    japanese: "Satō",
    russian: "сахар",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_044",
    english: "Salt",
    french: "Sel",
    spanish: "Sal",
    german: "Salz",
    japanese: "Shio",
    russian: "соль",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_045",
    english: "Pepper",
    french: "Poivre",
    spanish: "Pimienta",
    german: "Pfeffer",
    japanese: "Koshō",
    russian: "перец",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_046",
    english: "Ice cream",
    french: "Glace",
    spanish: "Helado",
    german: "Eiscreme",
    japanese: "Aisukurīmu",
    russian: "мороженое",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_047",
    english: "Cake",
    french: "Gâteau",
    spanish: "Pastel",
    german: "Kuchen",
    japanese: "Kēki",
    russian: "торт",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_048",
    english: "Cookie",
    french: "Biscuit",
    spanish: "Galleta",
    german: "Keks",
    japanese: "Kukkī",
    russian: "печенье",
    category: "food",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "food_049",
    english: "Yogurt",
    french: "Yaourt",
    spanish: "Yogur",
    german: "Joghurt",
    japanese: "Yōguruto",
    russian: "йогурт",
    category: "food",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "food_050",
    english: "Nuts",
    french: "Noix",
    spanish: "Nueces",
    german: "Nüsse",
    japanese: "Nattsu",
    russian: "орехи",
    category: "food",
    isCognate: false,
    difficulty: "medium"
  },

  // VEHICLES (50 words)
  {
    id: "vehicle_001",
    english: "Car",
    french: "Voiture",
    spanish: "Coche",
    german: "Auto",
    japanese: "Kuruma",
    russian: "машина",
    category: "vehicles",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "vehicle_002",
    english: "Bus",
    french: "Bus",
    spanish: "Autobús",
    german: "Bus",
    japanese: "Basu",
    russian: "автобус",
    category: "vehicles",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "vehicle_003",
    english: "Train",
    french: "Train",
    spanish: "Tren",
    german: "Zug",
    japanese: "Densha",
    russian: "поезд",
    category: "vehicles",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "vehicle_004",
    english: "Plane",
    french: "Avion",
    spanish: "Avión",
    german: "Flugzeug",
    japanese: "Hikōki",
    russian: "самолёт",
    category: "vehicles",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "vehicle_005",
    english: "Boat",
    french: "Bateau",
    spanish: "Barco",
    german: "Boot",
    japanese: "Fune",
    russian: "лодка",
    category: "vehicles",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "vehicle_006",
    english: "Bicycle",
    french: "Vélo",
    spanish: "Bicicleta",
    german: "Fahrrad",
    japanese: "Jitensha",
    russian: "велосипед",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_007",
    english: "Motorcycle",
    french: "Moto",
    spanish: "Motocicleta",
    german: "Motorrad",
    japanese: "Ōtobai",
    russian: "мотоцикл",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_008",
    english: "Truck",
    french: "Camion",
    spanish: "Camión",
    german: "Lastwagen",
    japanese: "Torakku",
    russian: "грузовик",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_009",
    english: "Taxi",
    french: "Taxi",
    spanish: "Taxi",
    german: "Taxi",
    japanese: "Takushī",
    russian: "такси",
    category: "vehicles",
    isCognate: true,
    difficulty: "easy"
  },
  {
    id: "vehicle_010",
    english: "Helicopter",
    french: "Hélicoptère",
    spanish: "Helicóptero",
    german: "Hubschrauber",
    japanese: "Herikoputā",
    russian: "вертолёт",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_011",
    english: "Ship",
    french: "Navire",
    spanish: "Barco",
    german: "Schiff",
    japanese: "Fune",
    russian: "корабль",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_012",
    english: "Subway",
    french: "Métro",
    spanish: "Metro",
    german: "U-Bahn",
    japanese: "Chikatetsu",
    russian: "метро",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_013",
    english: "Scooter",
    french: "Scooter",
    spanish: "Patinete",
    german: "Roller",
    japanese: "Sukūtā",
    russian: "скутер",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_014",
    english: "Ambulance",
    french: "Ambulance",
    spanish: "Ambulancia",
    german: "Krankenwagen",
    japanese: "Kyūkyūsha",
    russian: "скорая помощь",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_015",
    english: "Police car",
    french: "Voiture de police",
    spanish: "Coche de policía",
    german: "Polizeiauto",
    japanese: "Keisatsusha",
    russian: "полицейская машина",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_016",
    english: "Fire truck",
    french: "Camion de pompiers",
    spanish: "Camión de bomberos",
    german: "Feuerwehr",
    japanese: "Shōbōsha",
    russian: "пожарная машина",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_017",
    english: "Tram",
    french: "Tramway",
    spanish: "Tranvía",
    german: "Straßenbahn",
    japanese: "Toramu",
    russian: "трамвай",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_018",
    english: "Van",
    french: "Fourgonnette",
    spanish: "Furgoneta",
    german: "Lieferwagen",
    japanese: "Ban",
    russian: "фургон",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_019",
    english: "Rocket",
    french: "Fusée",
    spanish: "Cohete",
    german: "Rakete",
    japanese: "Roketto",
    russian: "ракета",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_020",
    english: "Skateboard",
    french: "Planche à roulettes",
    spanish: "Monopatín",
    german: "Skateboard",
    japanese: "Sukētobōdo",
    russian: "скейтборд",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_021",
    english: "Airplane",
    french: "Avion",
    spanish: "Avión",
    german: "Flugzeug",
    japanese: "Hikōki",
    russian: "самолёт",
    category: "vehicles",
    isCognate: false,
    difficulty: "easy"
  },
  {
    id: "vehicle_022",
    english: "Yacht",
    french: "Yacht",
    spanish: "Yate",
    german: "Yacht",
    japanese: "Yotto",
    russian: "яхта",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_023",
    english: "Canoe",
    french: "Canoë",
    spanish: "Canoa",
    german: "Kanu",
    japanese: "Kanū",
    russian: "каноэ",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_024",
    english: "Kayak",
    french: "Kayak",
    spanish: "Kayak",
    german: "Kajak",
    japanese: "Kayakku",
    russian: "каяк",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_025",
    english: "Ferry",
    french: "Ferry",
    spanish: "Ferry",
    german: "Fähre",
    japanese: "Ferī",
    russian: "паром",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_026",
    english: "Submarine",
    french: "Sous-marin",
    spanish: "Submarino",
    german: "U-Boot",
    japanese: "Sensuikan",
    russian: "подводная лодка",
    category: "vehicles",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "vehicle_027",
    english: "Trolleybus",
    french: "Trolleybus",
    spanish: "Trolebús",
    german: "Oberleitungsbus",
    japanese: "Tororebasu",
    russian: "троллейбус",
    category: "vehicles",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "vehicle_028",
    english: "Hovercraft",
    french: "Aéroglisseur",
    spanish: "Aerodeslizador",
    german: "Luftkissenboot",
    japanese: "Hobākurafuto",
    russian: "судно на воздушной подушке",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_029",
    english: "Bulldozer",
    french: "Bulldozer",
    spanish: "Bulldozer",
    german: "Bulldozer",
    japanese: "Burudōzā",
    russian: "бульдозер",
    category: "vehicles",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "vehicle_030",
    english: "Tractor",
    french: "Tracteur",
    spanish: "Tractor",
    german: "Traktor",
    japanese: "Torakutā",
    russian: "трактор",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_031",
    english: "Forklift",
    french: "Chariot élévateur",
    spanish: "Carretilla elevadora",
    german: "Gabelstapler",
    japanese: "Fōkurifuto",
    russian: "вилочный погрузчик",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_032",
    english: "Crane",
    french: "Grue",
    spanish: "Grúa",
    german: "Kran",
    japanese: "Kurēn",
    russian: "кран",
    category: "vehicles",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "vehicle_033",
    english: "Snowmobile",
    french: "Motoneige",
    spanish: "Moto de nieve",
    german: "Schneemobil",
    japanese: "Sunōmōbiru",
    russian: "снегоход",
    category: "vehicles",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "vehicle_034",
    english: "Jet ski",
    french: "Jet ski",
    spanish: "Moto de agua",
    german: "Jetski",
    japanese: "Jettosukī",
    russian: "гидроцикл",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_035",
    english: "Hot air balloon",
    french: "Montgolfière",
    spanish: "Globo aerostático",
    german: "Heißluftballon",
    japanese: "Kikyū",
    russian: "воздушный шар",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_036",
    english: "Rickshaw",
    french: "Pousse-pousse",
    spanish: "Rickshaw",
    german: "Rikscha",
    japanese: "Jinrikisha",
    russian: "рикша",
    category: "vehicles",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "vehicle_037",
    english: "Segway",
    french: "Segway",
    spanish: "Segway",
    german: "Segway",
    japanese: "Seguwē",
    russian: "сегвей",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_038",
    english: "Lawnmower",
    french: "Tondeuse à gazon",
    spanish: "Cortacésped",
    german: "Rasenmäher",
    japanese: "Shibakariki",
    russian: "газонокосилка",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_039",
    english: "Zeppelin",
    french: "Zeppelin",
    spanish: "Zepelín",
    german: "Zeppelin",
    japanese: "Tseperin",
    russian: "цеппелин",
    category: "vehicles",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "vehicle_040",
    english: "Glider",
    french: "Planeur",
    spanish: "Planeador",
    german: "Segelflugzeug",
    japanese: "Guraidā",
    russian: "планёр",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_041",
    english: "Wagon",
    french: "Chariot",
    spanish: "Carro",
    german: "Wagen",
    japanese: "Basha",
    russian: "повозка",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_042",
    english: "Sled",
    french: "Traîneau",
    spanish: "Trineo",
    german: "Schlitten",
    japanese: "Sori",
    russian: "сани",
    category: "vehicles",
    isCognate: false,
    difficulty: "medium"
  },
  {
    id: "vehicle_043",
    english: "Carriage",
    french: "Carrosse",
    spanish: "Carruaje",
    german: "Kutsche",
    japanese: "Basha",
    russian: "карета",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_044",
    english: "Hoverboard",
    french: "Hoverboard",
    spanish: "Hoverboard",
    german: "Hoverboard",
    japanese: "Hobābōdo",
    russian: "ховерборд",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_045",
    english: "Tugboat",
    french: "Remorqueur",
    spanish: "Remolcador",
    german: "Schlepper",
    japanese: "Tagubōto",
    russian: "буксир",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_046",
    english: "Freight train",
    french: "Train de marchandises",
    spanish: "Tren de carga",
    german: "Güterzug",
    japanese: "Kamotsu ressha",
    russian: "грузовой поезд",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_047",
    english: "Cable car",
    french: "Téléphérique",
    spanish: "Teleférico",
    german: "Seilbahn",
    japanese: "Kēburukā",
    russian: "канатная дорога",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  },
  {
    id: "vehicle_048",
    english: "Golf cart",
    french: "Voiturette de golf",
    spanish: "Carrito de golf",
    german: "Golfwagen",
    japanese: "Gorufu kāto",
    russian: "гольф-кар",
    category: "vehicles",
    isCognate: true,
    difficulty: "medium"
  },
  {
    id: "vehicle_049",
    english: "Bulldozer",
    french: "Bulldozer",
    spanish: "Bulldozer",
    german: "Bulldozer",
    japanese: "Burudōzā",
    russian: "бульдозер",
    category: "vehicles",
    isCognate: true,
    difficulty: "hard"
  },
  {
    id: "vehicle_050",
    english: "Horse-drawn cart",
    french: "Charrette à cheval",
    spanish: "Carro de caballos",
    german: "Pferdewagen",
    japanese: "Basha",
    russian: "телега",
    category: "vehicles",
    isCognate: false,
    difficulty: "hard"
  }
];

// Category information
export const CATEGORIES: CategoryInfo[] = [
  {
    id: "colors",
    name: "Colors",
    description: "Basic and advanced color names",
    wordCount: 50
  },
  {
    id: "animals",
    name: "Animals",
    description: "Common animals and creatures",
    wordCount: 50
  },
  {
    id: "food",
    name: "Food",
    description: "Food items, drinks, and ingredients",
    wordCount: 50
  },
  {
    id: "vehicles",
    name: "Vehicles",
    description: "Transportation and vehicles",
    wordCount: 50
  },
  {
    id: "clothing",
    name: "Clothing",
    description: "Clothes and accessories",
    wordCount: 50
  },
  {
    id: "sports",
    name: "Sports",
    description: "Sports and physical activities",
    wordCount: 50
  },
  {
    id: "household",
    name: "Household Items",
    description: "Common household objects and furniture",
    wordCount: 50
  }
];

// Utility functions for the word database
export function getWordsByCategory(category: string): WordEntry[] {
  return WORD_DATABASE.filter(word => word.category === category);
}

export function getRandomWordFromCategory(category: string): WordEntry | null {
  const words = getWordsByCategory(category);
  if (words.length === 0) return null;
  return words[Math.floor(Math.random() * words.length)];
}

export function getCategoryNames(): string[] {
  return CATEGORIES.map(cat => cat.id);
}

export function getCategoryInfo(categoryId: string): CategoryInfo | null {
  return CATEGORIES.find(cat => cat.id === categoryId) || null;
}

export function getWordTranslation(word: WordEntry, language: keyof Omit<WordEntry, 'id' | 'category' | 'isCognate' | 'difficulty'>): string {
  return word[language] as string;
}

export function getAllCognates(): WordEntry[] {
  return WORD_DATABASE.filter(word => word.isCognate);
}

export function getWordsByDifficulty(difficulty: 'easy' | 'medium' | 'hard'): WordEntry[] {
  return WORD_DATABASE.filter(word => word.difficulty === difficulty);
}

// Validation function to ensure database integrity
export function validateDatabase(): { isValid: boolean; errors: string[] } {
  const errors: string[] = [];
  const languages = ['english', 'french', 'spanish', 'german', 'japanese', 'russian'] as const;
  
  WORD_DATABASE.forEach((word, index) => {
    // Check if all required fields are present
    if (!word.id) errors.push(`Word at index ${index} missing ID`);
    if (!word.category) errors.push(`Word ${word.id} missing category`);
    
    // Check if all language translations are present
    languages.forEach(lang => {
      if (!word[lang] || word[lang].trim() === '') {
        errors.push(`Word ${word.id} missing ${lang} translation`);
      }
    });
    
    // Check if category exists
    if (!CATEGORIES.find(cat => cat.id === word.category)) {
      errors.push(`Word ${word.id} has invalid category: ${word.category}`);
    }
  });
  
  // Check category word counts
  CATEGORIES.forEach(category => {
    const actualCount = getWordsByCategory(category.id).length;
    if (actualCount !== category.wordCount) {
      errors.push(`Category ${category.id} claims ${category.wordCount} words but has ${actualCount}`);
    }
  });
  
  return {
    isValid: errors.length === 0,
    errors
  };
}

// Export database statistics
export function getDatabaseStats() {
  const totalWords = WORD_DATABASE.length;
  const cognateCount = getAllCognates().length;
  const difficultyStats = {
    easy: getWordsByDifficulty('easy').length,
    medium: getWordsByDifficulty('medium').length,
    hard: getWordsByDifficulty('hard').length
  };
  
  return {
    totalWords,
    totalCategories: CATEGORIES.length,
    cognateCount,
    cognatePercentage: Math.round((cognateCount / totalWords) * 100),
    difficultyStats,
    categoriesWithCounts: CATEGORIES.map(cat => ({
      ...cat,
      actualWordCount: getWordsByCategory(cat.id).length
    }))
  };
}